### ISSUE TITLE
the results differs from the paper

### ISSUE THREAD

**Issue by YuaCC** [bighuang624/AGAM#2]
I run the code with
`python train.py --train-data cub --test-data cub --backbone conv4 --num-shots 1 --train-tasks 50000 --semantic-type class_attributes --num-workers 0 --download`

and get the results:
```
 ./cub_cub_protonet_agam_conv4_2021-02-24-00-09-46
test_acc,71.08; 0.28
best_i_task,48000
best_train_acc,0.8233333826065063
best_train_loss,1.2430473566055298
best_val_acc,0.6532889052232107
best_val_loss,1.770083642800649
```
It differs from the result from paper 75.87;0.29
Would it be useful to run it multiple times？

**Comment by bighuang624** [comment]
@YuaCC  I think running it multiple times does help. The random seed is quite important in few-shot learning experiments as it also determines the sampling training and testing episodes.
