### ISSUE TITLE
Questions about the CUB dataset

### ISSUE THREAD

**Issue by Eve-88** [bighuang624/AGAM#5]
Does the CUB dataset need to be converted into hdf5 format? If so, can you release the hdf5 and json files you use?Thanks very much!

**Comment by bighuang624** [comment]
@Eve-88  Thanks for your attention. And you're right, the CUB dataset will be converted into hdf5 format with `--download` when running the program. We will look for a way to upload the hdf5 and json files, but it may take some time. We will try to finish it as soon as possible, and I will notice you in this issue when we finish it.

**Comment by bighuang624** [comment]
@Eve-88 Now you can get the hdf5 and json files from [https://drive.google.com/drive/folders/1OTEIOyki35K1XQ_qRUZJTG0h_q7MDtDR?usp=sharing](https://drive.google.com/drive/folders/1OTEIOyki35K1XQ_qRUZJTG0h_q7MDtDR?usp=sharing). Put these files into `AGAM/datasets/cub`, and then `--download` is no longer needed when running the program. We have not tested this, so feel free to reopen the issue if you find any problem. Thanks!

**Comment by Eve-88** [comment]
> @Eve-88 Now you can get the hdf5 and json files from https://drive.google.com/drive/folders/1OTEIOyki35K1XQ_qRUZJTG0h_q7MDtDR?usp=sharing. Put these files into `AGAM/datasets/cub`, and then `--download` is no longer needed when running the program. We have not tested this, so feel free to reopen the issue if you find any problem. Thanks!
Ok! thank you very much for sharing
