### ISSUE TITLE
About  accuracy problem

### ISSUE THREAD

**Issue by Eve-88** [bighuang624/AGAM#6]
I reproduced the experiment with the following settings on GeForce RTX 3090. The accuracy of the CUB dataset with conv4 is 2.61% and 5.68% lower than the original accuracy rate, respectively, and  my rate is 73.26% and 75.80%. The CUB dataset with resnet12 accuracy rate .The accuracy rates of the original text are 6.03% and 6.44% lower, respectively, and the accuracy rates of mine are 73.55% and 80.73% respectively; Is it reasonable to be so much lower than the original paper?  If it is unreasonable, I would like to ask, what is the reason for the difference in the experimental results?
{"model_name": "protonet_agam", "data_folder": "/home/hi/xx/AGAM-master/datasets/", "train_data": "cub", "test_data": "cub", "backbone": "resnet12", "lr": 0.001, "num_shots": 5, "num_ways": 5, "test_shots": 15, "batch_tasks": 4, "train_tasks": 40000, "val_tasks": 600, "test_tasks": 10000, "augment": true, "schedule": [15000, 30000, 45000, 60000], "gamma": 0.1, "valid_every_tasks": 1000, "num_workers": 2, "download": true, "use_cuda": true, "multi_gpu": true, "resume": false, "resume_folder": null, "ca_trade_off": 1.0, "sa_trade_off": 0.1, "addition_loss": "norm_softmargin", "semantic_type": ["class_attributes"], "record_folder": "./cub_cub_protonet_agam_resnet12_2022-04-05-14-06-32", "image_len": 84, "semantic_size": 312, "out_channels": 512, "feature_h": 5}

**Comment by bighuang624** [comment]
As discusses in [the previous issue](https://github.com/bighuang624/AGAM/issues/2), we did find that the randomness had a great influence on the results. So running the experiment multiple times may help. However, the results you reported were surprisingly poor, especially when using ResNet-12. We will consider uploading a copy of trained weights to facilitate validation.

**Comment by Eve-88** [comment]
> As discusses in [the previous issue](https://github.com/bighuang624/AGAM/issues/2), we did find that the randomness had a great influence on the results. So running the experiment multiple times may help. However, the results you reported were surprisingly poor, especially when using ResNet-12. We will consider uploading a copy of trained weights to facilitate validation.

Ok,looking forward to your update.

**Comment by bighuang624** [comment]
@Eve-88  Hi, sorry for this late response as there happened to be some problems with the file system of our GPU server. We have uploaded the weights now, and please refer to [the evalution steps](https://github.com/bighuang624/AGAM#evaluation). We just fixed our server, so we didn't have enough time to fully test it. Welcome to reopen the issue if you find any problem.
