### ISSUE TITLE
请问报这个错是为什么呢？

### ISSUE THREAD

**Issue by JaniceSu-su** [bighuang624/AGAM#9]
Traceback (most recent call last):
  File "D:/AGAM/models/agam/train.py", line 145, in <module>
    args.semantic_size = get_semantic_size(args)
  File "D:\AGAM\global_utils.py", line 96, in get_semantic_size
    for semantic_type in args.semantic_type:
TypeError: 'NoneType' object is not iterable

**Comment by bighuang624** [comment]
@JaniceSu-su 看上去是你没有输入 --semantic-type。你是 follow [我们给的 training 命令](https://github.com/bighuang624/AGAM#training)来跑的吗？最好是提供包括你的运行命令等更多的信息来帮助我们看怎么解决你遇到的问题。

**Comment by bighuang624** [comment]
Due to no further feedback, we have closed this issue. Please feel free to reopen it if there are new problems.
